const geminiButton = document.getElementById('gemini-button');
const taurusButton = document.getElementById('taurus-button');
const ariesButton = document.getElementById('aries-button');
const piscesButton = document.getElementById('pisces-button');
const aquariusButton = document.getElementById('aquarius-button');
const capricornButton = document.getElementById('capricorn-button');
const sagittariusButton = document.getElementById('sagittarius-button');
const ophiuchusButton = document.getElementById('ophiuchus-button');
const scorpioButton = document.getElementById('scorpio-button');
const libraButton = document.getElementById('libra-button');
const virgoButton = document.getElementById('virgo-button');
const leoButton = document.getElementById('leo-button');
const cancerButton = document.getElementById('cancer-button');
const generalinfoButton = document.getElementById('generalinfo-button');
const buttonClear = document.getElementById('button-clear');

const outputParagraph = document.getElementById ('output');

generalinfoButton.addEventListener ('click', () => {
    outputParagraph.innerText = "A constellation is an area on the celestial sphere in which a group of visible stars forms a perceived pattern or outline, typically representing an animal, mythological subject, or inanimate object. The word constellation comes from the Late Latin term cōnstellātiō, which can be translated as set of stars; it came into use in Middle English during the 14th century. The first constellations likely go back to prehistory. People used them to relate stories of their beliefs, experiences, creation, and mythology. Over time, among European astronomers, the constellations became clearly defined and widely recognised. In the 20th century, the International Astronomical Union (IAU) recognized 88 constellations. Constellation positions change throughout the year due to night on Earth occurring at gradually different portions of its orbit around the Sun. As Earth rotates toward the east, the celestial sphere appears to rotate west, with stars circling counterclockwise around the northern pole star and clockwise around the southern pole star.";
})

geminiButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Gemini is one of the constellations of the zodiac and is located in the northern celestial hemisphere. The figure of the constellation is easy to trace in the sky, thanks to the pair of bright stars named after the twin Dioscuri of Greek mythology: Castor (α Geminorum), a well-known telescopic binary star (actually composed of six stars), and Pollux (β Geminorum), which despite its assigned Greek letter is the brightest in the constellation. These two are counterbalanced by the star Alhena (γ Geminorum), located on the opposite side of the constellation. The most favorable time for its observation in the evening sky is from December to May. In Greek mythology, Gemini was associated with the myth of Castor and Pollux, the children of Leda and Argonauts both. Pollux was the son of Zeus, who seduced Leda, while Castor was the son of Tyndareus, king of Sparta and Leda's husband. Castor and Pollux were also mythologically associated with St. Elmo's fire in their role as the protectors of sailors. When Castor died, because he was mortal, Pollux begged his father Zeus to give Castor immortality, and he did, by uniting them together in the heavens.";
});

taurusButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Taurus is one of the constellations of the zodiac and is located in the northern celestial hemisphere. Taurus is a medium to large constellation located in the Northern Hemisphere that is easy to spot and well known. Its best-known feature by far is the presence of the brilliant Pleiades cluster, the brightest cluster of stars in the entire celestial vault. Despite being a boreal constellation, Taurus is well observable from all inhabited areas of Earth, thanks to its not very high declination; the most favorable period for its observation in the evening sky is from October to April. In Greek mythology, Taurus was identified with Zeus, who assumed the form of a magnificent white bull to abduct Europa, a legendary Phoenician princess.";
})

ariesButton.addEventListener('click', () => {
    outputParagraph.innerText = "Aries is one of the constellations of the zodiac. It is located in the Northern celestial hemisphere between Pisces to the west and Taurus to the east. It is a relatively small constellation: in fact, it occupies 441 square degrees of celestial vault, or slightly more than half the size of neighboring Taurus. However, its stars are quite conspicuous. The constellation becomes visible in the evening sky at the end of the boreal summer (September) and remains visible throughout autumn and winter, until March. Aries was not fully accepted as a constellation until classical times. In Hellenistic astrology, the constellation of Aries is associated with the golden ram of Greek mythology that rescued Phrixus and Helle on orders from Hermes, taking Phrixus to the land of Colchis.";
})

piscesButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Pisces is a constellation of the zodiac. Its vast bulk – and main asterism viewed in most European cultures per Greco-Roman antiquity as a distant pair of fishes connected by one cord each that join at an apex – are in the Northern celestial hemisphere. Pisces is associated with the Greek legend that Aphrodite and her son Eros either shape-shifted into forms of fishes to escape, or were rescued by two fishes. In the Greek version according to Hyginus, Aphrodite and Eros while visiting Syria fled from the monster Typhon by leaping into the Euphrates River and transforming into fishes. In 7 B.C., the possible year of Jesus' birth, there would have been a triple conjunction of Jupiter, Saturn and Mars in the constellation of Pisces. This astrological phenomenon in the sky would have appeared as the well-known Star of Bethlehem that showed the Magi the way to the newly born Messiah. The story of Jesus then shows other similarities with Pisces: the symbol of Christianity was originally a fish; many of his disciples were fishermen; a miracle of Jesus was the multiplication of the loaves and fishes.";
})

aquariusButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Aquarius is a large constellation, crossed by the Sun from late February to mid-March; it is made up of a vast collection of dimly lit stars, especially in the eastern part, a feature that would have suggested the idea of a veritable “cascade” of stars, which in fact represent water cascading down from an urn. In the celestial charts Aquarius is a young man pouring water from a pitcher, although in his Fasti Ovid claimed it was a mixture of water and nectar, the drink of the gods. The liquid goes into the mouth of the Southern Fish. The most popular belief identifies him with Ganymede, who was believed to be the most handsome boy existing on the face of the earth. He was the son of King Trous, after whom Troy was named. One day, while Ganymede was guarding his father's sheep, Zeus took a fancy to the shepherd boy and swooped down on the plain of Troy in the form of an eagle, gherminated Ganymede and took him to Olympus (or, according to another version, sent an actual eagle to do the job for him). The Eagle is remembered in the neighboring constellation.";
})

capricornButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Capricorn is a constellation of the zodiac. This constellation is the smallest of the zodiac's constellations, as well as one of the faintest after Pisces and Cancer; however, its most conspicuous stars are arranged to form an easy-to-recognize triangle. The most favorable time for its observation in the evening sky is from mid-summer to mid-autumn from the northern hemisphere, while from the southern hemisphere, where, by the way, the constellation is located, it is well observable during most of the year, with the exception of the southern summer. This constellation is one of the oldest constellations that have been defined, despite its faint brightness. Drawings of a capricorn or similar have been found on Babylonian tablets from about three thousand years ago. the Greeks, who called it Aegoceros (horned goat), identified the constellation with Pan, a country god who had goat horns and legs. Pan, a playful creature of uncertain birth, spent much of his time chasing women or snoozing. He could scare people by his particularly loud cry, from which the word “panic” originated.";
})

sagittariusButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Sagittarius is a constellation of the zodiac, commonly depicted as a centaur. The constellation is easily recognized by an asterism known as the Teapot: the stars Kaus Media (δ Sagittarii), Kaus Australis (ε Sagittarii), Ascella (ζ Sagittarii) and φ Sagittarii form the body of the teapot, Kaus Borealis (λ Sagittarii) is the lid, Alnasl (γ Sagittarii) is the spout, and Nunki (σ Sagittarii) and τ Sagittarii are the handle. In the Northern Hemisphere, Sagittarii is a characteristic figure of summer nights: it appears rather low on the southern horizon and can be observed in the evening sky without difficulty only in the period between June and September; in the Southern Hemisphere, however, it is a characteristic and dominant figure in winter skies. In the sky, Sagittarius is depicted as an archer, with the lower part of the body, including the four legs, of a horse and the upper part of a man. He wears a cloak and stretches a bow pointed in the direction of neighboring Scorpio. Sagittarius is a constellation of Sumerian origin, later adopted by the Greeks";
})

ophiuchusButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Ophiuchus is one of the 88 modern constellations however it is not normally considered a constellation of the zodiac and is the only one not named after an astrological sign. The constellation straddles the celestial equator in an area northwest of the center of the Milky Way; this position means that it is fully visible from almost all areas of the Earth, with the exception of the polar regions. The Greeks identified Ophiuchus with Asclepius, the god of medicine. Asclepius was the son of Apollo and Coronides. Legend has it that Coronides betrayed Apollo with a mortal, Ischys, while she was pregnant with Apollo's child. A raven, a bird that had hitherto been candid, brought the god the bad news but instead of the reward he expected he was cursed by the god who turned him black. In a fit of jealousy Apollo struck Coronides with an arrow. Rather than see his child die with her, the god snatched the fetus from its mother's womb as the flames of the funeral pyre enveloped it, and entrusted it to Chiron, the wise centaur (represented in the sky by the constellation Centaur). Chiron raised Asclepius like a son and taught him the supernatural techniques of healing and hunting. Asclepius became so skilled in medicine that he was not only able to save lives but even to raise the dead; Asclepius is considered the greatest physician of antiquity.";
})

scorpioButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Scorpio is a constellation of the zodiac; it lies between Libra in the west and Sagittarius in the east. Scorpio is not a particularly large constellation, but it contains an arrangement of bright stars that well resemble the figure of a scorpion; it lies near the center of the Milky Way, between the constellations of Ophiuchus and Sagittarius. Its most conspicuous star is the red Antares, the heart of the scorpion. Scorpio is a constellation in the southern hemisphere; from European regions it is observable in its entirety only from the Mediterranean coast, that is, from the 45th parallel north. In the southern hemisphere, on the other hand, it is well visible for most of the year; the best months for its observation, however, are those corresponding to the boreal summer, from May to August. In the northern hemisphere it is one of the most typical figures of the summer skies: its setting just after the sun goes down indicates that summer is drawing to a close. Originally, the part of the sky known to us as Libra was in fact occupied by the claws of Scorpio. The Greeks called this area Chelai[7] (Latin Chelae), meaning precisely “claws,” an identification that persists in the names of the individual stars of Libra. Today, after separation, Libra is a constellation barely larger than Scorpio, but much less visible. In mythology this is the scorpion that stung Orion the hunter to death, although there are different accounts as to the circumstances under which this happened.";
})

libraButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Libra is one of the 12 constellations of the zodiac. It is a relatively inconspicuous constellation as the bright constellations of Virgo and Scorpio, between which Libra is squeezed, help to obscure it. The most suitable time for its observation is between the months of April and July, from the northern hemisphere, and for a few more months from the southern hemisphere; observers in the northern hemisphere are also at a disadvantage because the period of maximum visibility coincides with the gradual increase in daylight hours in spring evenings, a fact that greatly reduces the hours for its observation. Originally, the part of the sky known to us as Libra was occupied by the claws of Scorpio. The Greeks called this area Chelai (Latin Chelae), meaning precisely “claws,” an identification that persists in the names of the individual stars of Libra.";
})

virgoButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Virgo is part of the 12 constellations of the zodiac. It lies between Leo in the west and Libra in the east, and is one of the largest constellations in the sky. The constellation straddles the celestial equator, north of the tail of Hydra and Centaurus; Virgo dominates the skies from February through July, and contains within it some very bright stars. It is uncertain who exactly one wants to represent with Virgo. Over the years, it has been associated with almost every famous goddess, including Astarte-Ištar, Cybele, Demeter, Isis, Athena, Tiche, Astrea and so on. According to one version, the constellation depicts Astrea, the virgin daughter of the god Zeus and the goddess Temi. Astrea was known as the goddess of justice (and because of this, the instrument of justice, Libra, is located near there). According to legend, she administered the world wisely, until men became so intractable that she retired to the heavens in disgust. But also with Erigone, who seduced and abandoned by Dionysus and committed suicide after the death of her father Icarius. Virgo is also often associated with Persephone because the constellation is mainly visible in the spring months, when the goddess was thought to have emerged from the world of shadows. It is said that she had to retreat into darkness to preserve purity, a symbol of beauty, and with the help of the scales, a cosmic executioner, return to being the universal center.";
})

leoButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Leo is a zodiac constellation of the northern sky; in fact, it lies along the line of the ecliptic, between the faint constellation Cancer in the west and the vast Virgo in the east. Leo is a large zodiacal constellation of the northern hemisphere, easily spotted in the months between December and June; in the northern hemisphere, its presence in the east after sunset indicates the imminent arrival of spring, while in the southern hemisphere it becomes a typical constellation of the late summer and autumn skies. Eratostenes and Hyginus claim that the lion was placed in the sky because it is the king of animals. In mythological terms, it is believed to be the Nemean lion, defeated by Hercules in the first of his twelve labors. Hercules was surprised by the beast while traveling through the woods. The lion broke his armor with the blows of its claws. The hero managed to block one of the entrances to the beast's den and enter the other. In the terrible hand-to-hand duel, the lion tore off one of Hercules' fingers, but in the end the hero grabbed the beast by the head and thick mane, and the lion gradually slumped to the ground defeated. Hercules shouldered him in triumph and carried him to Mycenae, where he terrified Eurystheus, who ordered him to bring him back. Hercules did so. Upon death, the Nemean lion was placed by Zeus among the signs of the zodiac, where it formed the constellation of the lion.";
})

cancerButton.addEventListener ('click', () => {
    outputParagraph.innerText = "Cancer is a constellation of the zodiac. Although it is a medium-sized constellation, it is definitely not very bright. It lies between Gemini in the west and Leo in the east; to the north it is bordered by the Lynx and to the south by the Cane Minor and Hydra. The constellation Cancer contains no particularly bright stars, although its size is comparable to Gemini. Cancer is all in the northern hemisphere, so it is well observable from regions north of the equator; the suitable period for its observation in the evening sky is from December until May. From the southern hemisphere it is observable for a more limited period, since it occurs, especially in temperate regions, relatively low. The crab is a minor character in one of the Labors of Heracles (the Greek name for Hercules). As Heracles struggled against the many-headed monster named Hydra in the swamp near Lerna, the crab emerged from the ooze and participated in the attack by pinching the hero's foot, which stomped on it furiously, reducing it to mush. It is said that for this modest contribution to history, the goddess Hera, Heracles' enemy, reserved for him a place among the stars of the zodiac. ";
})

buttonClear.addEventListener ('click', () => {
    outputParagraph.innerText = " ";
})